### PR TITLE
Added Import-ActiveDirectory

### PR DESCRIPTION
**Pull request by Dliv3**
This powershell script will import AD module without writing files to disk.

### CODE REVIEW

**Comment by samratashok** [comment]
I like this. Could you please add an example of converting the DLL to the array. I mean, I know the method but it would be good to have it in the script as well.

**Comment by Dliv3** [comment]
I added an ActiveDirectoryModule parameter that supports reading and loading dll files from disk.

**Comment by samratashok** [comment]
Sweet! This will be merged soon!

**Comment by Dliv3** [comment]
Any progress？

**Comment by samratashok** [comment]
Merging this. Will make some changes post merge. Thanks for the contribution :)

**Pull request merged**
